name: CI
on: [push, pull_request]
permissions:
    contents: read

jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-2019]
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                fetch-depth: 10

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Install calibre dependencies
              run:
                  python setup/unix-ci.py install

            - name: Bootstrap calibre
              run:
                  python setup/unix-ci.py bootstrap

            - name: Test calibre
              env:
                PYTHONWARNINGS: error
                CALIBRE_SHOW_DEPRECATION_WARNINGS: 1
              run:
                  python setup/unix-ci.py test

            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@v2
              with:
                  retain_days: 14
